-- what is total revenue generated by male vs female customers

select gender,sum(purchase_amount) AS total_cost
from customer_sales_data
group by gender; 

-- which customer used the discount but still spend more than average purchase amount

select customer_id,purchase_amount, discount_applied
from customer_sales_data
where discount_applied = 'Yes' and purchase_amount >
(select avg(purchase_amount) as average
from customer_sales_data)
;

-- what are the top 5 products with highest average review rating 

select item_purchased , round(AVG(review_rating::numeric),2) as Average
from customer_sales_data
group by item_purchased
order by Average DESC
limit 5;

-- compare the average purchase amount between standard and express shipping 

select shipping_type , round(Avg(purchase_amount::numeric),2) as Average
from customer_sales_data
where shipping_type = 'Express' or shipping_type = 'Standard'
group by shipping_type
;

-- Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers

select subscription_status,Count(customer_id) AS total_customers, sum(purchase_amount) as total_revenue , round(Avg(purchase_amount::numeric),2) As Average_revenue
from customer_sales_data
group by subscription_status
;

-- which 5 products have the highest percantage of purchases with discount applied 

select item_purchased ,
round(100 * sum(case when discount_applied = 'Yes' Then 1 else 0 end )/count(item_purchased),2) as discount_rate
from customer_sales_data
group by item_purchased 
order by discount_rate DESC
limit 5;

-- segment customers into new, returning and loyal based on their total number of previous purchases, and show the count of each segments

with customer_type as (
select customer_id,previous_purchases,
Case
    when previous_purchases = 1 then 'new'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'loyal'
	end as customer_segment
from customer_sales_data
)
select customer_segment,count(customer_id) as number_of_customers
from customer_type
group by customer_segment
;

-- what are top 3 most purchased products with-in each cateory 

with item_counts as (
select category , item_purchased , count(customer_id) as total_customers,
ROW_NUMBER() over(
      partition by category
	  order by count(customer_id) desc) as item_rank
from customer_sales_data
group by category , item_purchased
)
select item_rank,category,item_purchased,total_customers
from item_counts
where item_rank <= 3;

-- are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status , count(customer_id) as total_customers
from customer_sales_data
where previous_purchases > 5 
group by subscription_status
;

-- what is the revenue contribution of each age group ?

select age_group , sum(purchase_amount) as total_revenue
from customer_sales_data
group by age_group
order by total_revenue DESC
limit 5
;



